(function(){
'use strict';
var selectedShape='auto',selectedTheme='auto';
var shapes=[['auto','Auto'],['round','Round'],['circle','Circle'],['square','Square'],['rectangle','Rectangle'],['tower','Tower'],['heart','Heart'],['bundt','Bundt']];
var themes=[['auto','✨ Auto'],['classic','🎂 Classic'],['fairytale','👑 Fairytale'],['mouse','🐭 Cartoon Mouse'],['race','🏁 Race Cars'],['space','🚀 Space'],['princess','👸 Princess'],['jungle','🌿 Jungle']];
var themeData={
 classic:{label:'Classic Cake',icon:'🎂',colors:['#f8dfa9','#fff7df','#fff'] ,badges:[['🍒','8%','72%'],['✨','78%','18%']]},
 fairytale:{label:'Fairytale Castle',icon:'👑',colors:['#f4cfe4','#ffe2ad','#fff8ff'],badges:[['👑','8%','18%'],['🏰','76%','69%'],['✨','78%','18%']]},
 mouse:{label:'Cartoon Mouse Party',icon:'🐭',colors:['#303030','#d94c62','#fff'],badges:[['🐭','8%','20%'],['🎀','77%','18%'],['⭐','18%','73%']]},
 race:{label:'Race Car Party',icon:'🏁',colors:['#ffd34c','#fff','#292929'],badges:[['🏁','8%','18%'],['🚗','76%','22%'],['⚡','18%','73%']]},
 space:{label:'Space Party',icon:'🚀',colors:['#30366f','#6176db','#eef2ff'],badges:[['🚀','8%','18%'],['🌙','77%','20%'],['⭐','18%','73%']]},
 princess:{label:'Princess Party',icon:'👸',colors:['#ffc3dc','#ffe4f0','#fff7fb'],badges:[['👸','8%','18%'],['💖','77%','20%'],['👑','18%','73%']]},
 jungle:{label:'Jungle Party',icon:'🌿',colors:['#6aa35e','#94c77c','#f5ffef'],badges:[['🌿','8%','18%'],['🦁','77%','20%'],['🌺','18%','73%']]}
};
function cake(){return document.getElementById('cake')}
function addDecor(){var c=cake();if(!c)return null;var d=document.getElementById('themeDecor');if(!d){d=document.createElement('div');d.id='themeDecor';d.className='theme-decor';c.insertBefore(d,c.firstChild)}return d}
function renderPanel(){var zone=document.querySelector('.platezone');if(!zone)return;var panel=document.getElementById('cakeCustomPanel');if(!panel){panel=document.createElement('section');panel.id='cakeCustomPanel';panel.className='cake-custom-panel';var actions=document.querySelector('.actions');(actions||zone).insertAdjacentElement('afterend',panel)}panel.innerHTML='<div class="custom-row"><div class="custom-title">Cake shape options</div><div class="custom-chips">'+shapes.map(function(x){return '<button type="button" class="custom-chip '+(selectedShape===x[0]?'active':'')+'" data-shape="'+x[0]+'">'+x[1]+'</button>'}).join('')+'</div></div><div class="custom-row"><div class="custom-title">Cake theme options</div><div class="custom-chips">'+themes.map(function(x){return '<button type="button" class="custom-chip '+(selectedTheme===x[0]?'active':'')+'" data-theme="'+x[0]+'">'+x[1]+'</button>'}).join('')+'</div></div><div class="custom-note">Fairytale, cartoon-mouse and race-car themes are original alternatives, not licensed Disney, Mickey Mouse or Pixar Cars artwork.</div>';panel.querySelectorAll('[data-shape]').forEach(function(b){b.addEventListener('click',function(){selectedShape=b.dataset.shape;renderPanel();apply()})});panel.querySelectorAll('[data-theme]').forEach(function(b){b.addEventListener('click',function(){selectedTheme=b.dataset.theme;renderPanel();apply()})})}
function resetShapeLayers(){var c=cake();if(!c)return;c.querySelectorAll('.layer').forEach(function(x){x.style.display=''})}
function apply(){var c=cake();if(!c||!c.classList.contains('show'))return;if(selectedShape!=='auto'){Array.from(c.classList).filter(function(x){return x.indexOf('shape-')===0}).forEach(function(x){c.classList.remove(x)});c.classList.add('shape-'+selectedShape);resetShapeLayers()}var d=addDecor();if(selectedTheme==='auto'){d.innerHTML='';d.className='theme-decor';return}var t=themeData[selectedTheme]||themeData.classic;d.className='theme-decor theme-'+selectedTheme;d.innerHTML='<div class="theme-ribbon">'+t.label+'</div>'+t.badges.map(function(x){return '<span class="theme-badge" style="left:'+x[1]+';top:'+x[2]+'">'+x[0]+'</span>'}).join('');var layers=c.querySelectorAll('.layer');layers.forEach(function(x,i){x.style.background=t.colors[i%2]});var f=document.getElementById('frost');if(f){f.style.background=t.colors[2];f.style.color=t.colors[2]}var top=document.getElementById('topper');if(top)top.textContent=t.icon}
function install(){renderPanel();addDecor();var c=cake();if(c)new MutationObserver(function(){setTimeout(apply,30)}).observe(c,{attributes:true,attributeFilter:['class']});var bake=document.getElementById('bake');if(bake)bake.addEventListener('click',function(){setTimeout(apply,3400)},true);document.addEventListener('click',function(e){if(e.target.closest('#clear')){var d=addDecor();if(d)d.innerHTML=''}},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();